name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@40.90.249.111 << EOF
          cd ~
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || true
          cd simple-api
          git pull
          npm install
          sudo npm install -g pm2
          pm2 stop simple-api || true
          pm2 start ecosystem.config.js
          sudo env PATH=\$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u azureuser --hp /home/azureuser
          pm2 save
        EOF